modulo-3/my_firts_app/config/routes.rb
Rails.application.routes.draw do
  get 'translators/translate'

  get 'translators/detect'

  get 'translators/lenguages'

  get 'greeter/hello' => "greeter#hello"
  get 'greeter/goodbye'
  get 'greeter/remember'

  root "translators#lenguages"

end

modulo-3/my_firts_app/app/models/google_translate.rb
class GoogleTranslate
  include HTTParty
  default_options.update(verify: false)
  base_uri "https://www.googleapis.com/language/translate/v2"
  format :json

  @@api_key = "AIzaSyBdqiJZunlGxiU5ubdmKlp2VqxqR7GYLsQ"

  default_params key: @@api_key

  attr_accessor :source, :target, :text

  def initialize(source, target)
    @source = source
    @target = target
  end

  def translate(search)
    options = { query: {q: search, source:@source, target:@target}}
    response = self.class.get("", options)
    if response.success?
      response
    else
      raise response.response
    end
  end

  def self.detect(target_language)
    options = { query: {q: target_language}}
    response = get("/detect", options)
    if response.success?
      response
    else
      raise response.response
    end
  end

  def self.languages(target)
    options = { query: {target: target}}
    response = get("/languages", options)
    if response.success?
      response
    else
      raise response.response
    end
  end

end

modulo-3/my_firts_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

modulo-3/my_firts_app/app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
  	random_names = ["vanessa", "lorena", "lourdes"]
  	@name = random_names.sample
  	@time= Time.now
  	@times_displayed ||=0
  	@times_displayed +=1
  end

  def goodbye
  end

  def remember
  end
end

modulo-3/my_firts_app/app/controllers/translators_controller.rb
class TranslatorsController < ApplicationController
  def translate
  	@google = GoogleTranslate.new("en", "es")
  	@trans = params[:text] || "This is a really good party!"
  	@response = @google.translate(@trans)
  	@translations = @response['data']['translations'][0]['translatedText']
  end

  def detect
  	@trans = "This is a really party!"
  	@detection = GoogleTranslate.detect(@trans)
  	puts "#{@detection}"
  end

  def lenguages
  	@target_language = "fr"
  	@languages = GoogleTranslate.languages(@target_language)
  	puts "Es posible traducir desde los siguientes idiomas: #{@languages}"
  end
end

modulo-3/my_firts_app/app/helpers/application_helper.rb
module ApplicationHelper
end

modulo-3/my_firts_app/app/helpers/greeter_helper.rb
module GreeterHelper
	def formatted_time(time)
		time.strftime("%I:%M:%p")
	end
end

modulo-3/my_firts_app/app/helpers/translators_helper.rb
module TranslatorsHelper
end

modulo-3/my_firts_app/app/views/greeter/goodbye.html.erb
<% random_names = ["vannessa", "lorena", "lourdes"] %>
<h1> goodbye, <%= random_names.sample %></h1>
<p>La hora es: <%=Time.now %></p>

modulo-3/my_firts_app/app/views/greeter/hello.html.erb
<h1> Gretings, <%= @name	 %></h1>
<p>La hora es: <%= formatted_time(@time) %></p>
<p>Esta pagina se ha mostrado en:
	<%= @times_displayed%>
	<%= @times_displayed == 1 ? "vez": "veces"%>
</p>
<p><%= link_to "Google", "http://www.google.com" %></p>
<p><%= link_to "Good bye", greeter_goodbye_path %></p>

modulo-3/my_firts_app/app/views/greeter/remember.html.erb
<% random_names = ["vannessa", "lorena", "lourdes"] %>
<h1> Gretings, <%= random_names.sample %></h1>
<h1> hello, sample_name, of curse we remember you!</h1>

modulo-3/my_firts_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirtsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

modulo-3/my_firts_app/app/views/translators/detect.html.erb
<h1>Detected language !</h1>
<h2><%= @detection['data']['detections'][0][0]['language'] %></h2>

modulo-3/my_firts_app/app/views/translators/lenguages.html.erb
<h1>Idiomas en- <%= @target_language %></h1><table border="1">
 <tr>
   <th>Language</th>
   <th>Name</th>
 </tr>
 <% @languages['data']['languages'].each do |lang| %>
   <tr class=<%= cycle('even', 'odd') %>>
     <td><%= lang['name'] %></td>
     <td><%= lang['language'] %></td>
   </tr>
 <% end %>
</table>

modulo-3/my_firts_app/app/views/translators/translate.html.erb
<h1>Translated text!</h1>

<p><%= @translations%></p>